In [1]:
input_string = input('Enter a string: ')

hhh=[]
for i in input_string:
    if i in hhh:
        print(i)
        break
    else:
        hhh.append(i)

Enter a string: jfkdjkfsjlk
j


In [2]:
fhand = input('Enter a string: ')
count = 0

vowels = set('aeiou')
for i in fhand:
    if i in vowels:
        count = count + 1
        print(i)
    else:
        pass
print(count)

Enter a string: aeioudklsls
a
e
i
o
u
5


In [3]:
string1 = input('Enter a string: ')
string2 = input('Enter a another string: ')

if len(string1) < 2 or len(string2) < 2:
    raise Exception('The length of string should be longer than 2.')

s1 = string1[2:]
s2 = string2[2:]

print(s1+s2)

Enter a string: flksjlkfjslfjsl
Enter a another string: rieorioeiroei
ksjlkfjslfjsleorioeiroei


In [4]:
row = input('Enter a string: ')
string = str(row)

dict = {}
for index,value in enumerate(string):
    dict[value]=index+1

items = dict.items()
items = sorted(items)
for key,value in items:
    print("pos(" + str(key) + ") =" + str(value))

Enter a string: aieusl
pos(a) =1
pos(e) =3
pos(i) =2
pos(l) =6
pos(s) =5
pos(u) =4


In [5]:
string = input('Enter a list: ')
lst = list(string)

dict = {}
for index,value in enumerate(lst):
    dict[value]=index+1

items = dict.items()
items = sorted(items)
for key,value in items:
    print("pos(" + str(key) + ") =" + str(value))

Enter a list: aiueopq
pos(a) =1
pos(e) =4
pos(i) =2
pos(o) =5
pos(p) =6
pos(q) =7
pos(u) =3


In [6]:
string1 = input('Enter a string: ')
string2 = input('Enter another string: ')

# the time complexity of my algorithm is O(m+n)

def isCommenNum(s1,s2):
    set2 = set(s2)
    for i in s1:
        if i in set2:
            print('True')
            return
        else:
            pass

isCommenNum(string1,string2)

Enter a string: isoakajf
Enter another string: jkiaoa
True


In [7]:
lst = []
while True:
    string = input('Enter a number.Input empty to quit.')
    if len(string) != 0:
        lst.append(string)
    else:
        break

if len(lst) % 2 == 1:
    tmp = lst[:-1:2]
    lst[:-1:2] = lst[1::2]
    lst[1::2] = tmp
else:
    tmp = lst[::2]
    lst[::2] = lst[1::2]
    lst[1::2] = tmp
print(lst)

Enter a number.Input empty to quit.12
Enter a number.Input empty to quit.23
Enter a number.Input empty to quit.4
Enter a number.Input empty to quit.45
Enter a number.Input empty to quit.56
Enter a number.Input empty to quit.
['23', '12', '45', '4', '56']


In [8]:
string = ''
for i in range(10):
    string = ''
    for j in range(10):
        value = i * j
        string = string + str(value) + ' '
    print(string)

0 0 0 0 0 0 0 0 0 0 
0 1 2 3 4 5 6 7 8 9 
0 2 4 6 8 10 12 14 16 18 
0 3 6 9 12 15 18 21 24 27 
0 4 8 12 16 20 24 28 32 36 
0 5 10 15 20 25 30 35 40 45 
0 6 12 18 24 30 36 42 48 54 
0 7 14 21 28 35 42 49 56 63 
0 8 16 24 32 40 48 56 64 72 
0 9 18 27 36 45 54 63 72 81 


In [9]:
from numpy import *
import numpy as np

M = np.random.randint(0,20,size=(10,10))
N = np.random.randint(0,20,size=(10,10))

C = M - N
print(C)

[[-14  10  10   6   3  11  17   8   5  -3]
 [ -5   0 -14   7  -9  -1   2   2  -8  -5]
 [ -3  -7  15   0   0  12  -9  -1  -4  -7]
 [ -6 -15 -11  11   9   1  -1 -14   7  -7]
 [  3  -6  -5  -4   8  10  -1  -3   2 -15]
 [  5  17  10  -6 -10  14 -19 -12   1  -5]
 [ 11  -6   2  16  11  -3   1  12   5 -14]
 [  9 -10  -1  18  -4 -17  -5 -13  11  -9]
 [ -8   4  -1 -16 -10   1 -11   4  15   6]
 [  7  11  -8   8   0   4   1  -7  -4   6]]
